### ISSUE TITLE
Fix BAIFA

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/BAIFA#1149]
BAIFA 改版後有異常，開單找出異常處並修復

- [x] 找出異常處開單（列在此工作單內）
- [x] #1150
- [x] #1151
- [x] #1152
- [x] #1153
- [x] #1155
- [x] #1156

**Comment by godmmt** [comment]
開完單後就要順便寫在週報上
因為週一請假
所以這週週報還沒寫
記得記得~

**Comment by godmmt** [comment]
Currencies List

db: 2 
dev: 0 (error!)
vercel: Application error: a client-side exception has occurred (see the browser console for more information).

**Comment by godmmt** [comment]
console error for run dev:

```bash
Error fetching currencies data (017): PrismaClientKnownRequestError: 
Invalid `prisma.currencies.findMany()` invocation:


Error converting field "id" of expected non-nullable type "String", found incompatible value of "1".
    at si.handleRequestError (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:125:6817)
    at si.handleAndLogRequestError (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:130:9805)
    at async handler (webpack-internal:///(api)/./src/pages/api/v1/app/currencies/index.ts:24:28)
    at async K (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:2871)
    at async U.render (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3955)
    at async DevServer.runApi (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/next-server.js:269:37)
    at async DevServer.handleRequestImpl (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/lib/router-server.js:353:24) {
  code: 'P2032',
  clientVersion: '5.8.1',
  meta: {
    modelName: 'currencies',
    field: 'id',
    expected_type: 'String',
    found: '1'
  }
}
 GET /api/v1/app/currencies?page=1&offset=10&sort=asc&search=&type= 500 in 316ms
Error fetching currencies data (017): PrismaClientKnownRequestError: 
Invalid `prisma.currencies.findMany()` invocation:


Error converting field "id" of expected non-nullable type "String", found incompatible value of "1".
    at si.handleRequestError (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:125:6817)
    at si.handleAndLogRequestError (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:130:9805)
    at async handler (webpack-internal:///(api)/./src/pages/api/v1/app/currencies/index.ts:24:28)
    at async K (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:2871)
    at async U.render (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3955)
    at async DevServer.runApi (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/next-server.js:269:37)
    at async DevServer.handleRequestImpl (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/lib/router-server.js:353:24) {
  code: 'P2032',
  clientVersion: '5.8.1',
  meta: {
    modelName: 'currencies',
    field: 'id',
    expected_type: 'String',
    found: '1'
  }
}
 GET /api/v1/app/currencies?page=1&offset=10&sort=asc&search=&type= 500 in 43ms
```

**Comment by godmmt** [comment]
Black List 沒有資料
Red Flag 沒有資料

要輸入假資料做測試

**Comment by Luphia** [comment]
需要假資料測試

**Comment by godmmt** [comment]
took 1 hour

先處理 #1150 後再繼續此單

**Comment by Luphia** [comment]
<img width="684" alt="截圖 2024-07-09 上午11 48 19" src="https://github.com/CAFECA-IO/BAIFA/assets/270062/e2e2d0ea-49a1-4eef-836a-ad9bb142a3a8">

區塊鏈列表 /app/chains
兩條鏈的區塊數字顛倒了

**Comment by godmmt** [comment]
上面的問題已開單 #1153

**Comment by godmmt** [comment]
目前沒發現異常

**Comment by godmmt** [comment]
Total time: 1 hour

done.
