### ISSUE TITLE
修復 console error from run dev

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/BAIFA#1150]
<details>

<summary>console error for run dev: </summary>

```bash
Error fetching currencies data (017): PrismaClientKnownRequestError: 
Invalid `prisma.currencies.findMany()` invocation:


Error converting field "id" of expected non-nullable type "String", found incompatible value of "1".
    at si.handleRequestError (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:125:6817)
    at si.handleAndLogRequestError (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:130:9805)
    at async handler (webpack-internal:///(api)/./src/pages/api/v1/app/currencies/index.ts:24:28)
    at async K (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:2871)
    at async U.render (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3955)
    at async DevServer.runApi (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/next-server.js:269:37)
    at async DevServer.handleRequestImpl (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/lib/router-server.js:353:24) {
  code: 'P2032',
  clientVersion: '5.8.1',
  meta: {
    modelName: 'currencies',
    field: 'id',
    expected_type: 'String',
    found: '1'
  }
}
 GET /api/v1/app/currencies?page=1&offset=10&sort=asc&search=&type= 500 in 316ms
Error fetching currencies data (017): PrismaClientKnownRequestError: 
Invalid `prisma.currencies.findMany()` invocation:


Error converting field "id" of expected non-nullable type "String", found incompatible value of "1".
    at si.handleRequestError (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:125:6817)
    at si.handleAndLogRequestError (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/Users/liz/Documents/Job_repo/BAIFA/node_modules/@prisma/client/runtime/library.js:130:9805)
    at async handler (webpack-internal:///(api)/./src/pages/api/v1/app/currencies/index.ts:24:28)
    at async K (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:2871)
    at async U.render (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3955)
    at async DevServer.runApi (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/next-server.js:269:37)
    at async DevServer.handleRequestImpl (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/liz/Documents/Job_repo/BAIFA/node_modules/next/dist/server/lib/router-server.js:353:24) {
  code: 'P2032',
  clientVersion: '5.8.1',
  meta: {
    modelName: 'currencies',
    field: 'id',
    expected_type: 'String',
    found: '1'
  }
}
 GET /api/v1/app/currencies?page=1&offset=10&sort=asc&search=&type= 500 in 43ms
```

</details>

----

這裡的錯誤是跟 currencies & currencyId page 這兩個頁面有關

**Comment by godmmt** [comment]
Error:

TypeError: Cannot destructure property 'unit' of 'currencyData' as it is undefined.

**Comment by godmmt** [comment]
之前的 dummyCurrencyDetailString 被刪除了
但刪除者似乎沒有去修改文件讓程式碼可行
所以造成錯誤

```
export const dummyCurrencyDetailString: ICurrencyDetailString = {
  currencyId: '',
  currencyName: '',
  rank: 0,
  riskLevel: '',
  chainId: '',
  price: 0,
  volumeIn24h: 0,
  unit: '',
  totalAmount: '',
  holderCount: 0,
  totalTransfers: 0,
  flagging: [],
  flaggingCount: 0,
};
```

**Comment by godmmt** [comment]
- [x] 確認錯誤原因

本次修改方向為：
修改為抓不到資料後
顯示 No data

**Comment by godmmt** [comment]
相關的 API 是這支

```ts
  // Info: (20240321 - Liz) Call API to get currency data (API-018)
  const {
    data: currencyDataRaw,
    isLoading: isCurrencyDataLoading,
    error: currencyDataError,
  } = useAPIResponse<ICurrencyDetailString>(`${APIURL.CURRENCIES}/${currencyId}`, {
    method: HttpMethod.GET,
  });
```

**Comment by godmmt** [comment]
這裡的 prop type 被修改成 Number
但相關的程式碼邏輯沒有改
所以出現錯誤

```ts
interface ICurrencyDetailPageProps {
  currencyId: number;
}
```

**Comment by godmmt** [comment]
```
src/components/all_currencies_page_body/all_currencies_page_body.tsx
```

**Comment by godmmt** [comment]
因為之前邏輯寫的 currency id 是 string
被改成 number 後
但邏輯並沒有跟著修改

所以要修復此部分。

有用到的部分像是圖片 icon 的拿取
以及檢查以下的文件
src/pages/app/currencies/[currencyId]/index.tsx
src/components/all_currencies_page_body/all_currencies_page_body.tsx
src/components/currency_item/currency_item.tsx

**Comment by godmmt** [comment]
修改 currencyId 改回原本的 string

```ts
interface ICurrencyDetailPageProps {
  currencyId: string;
  // Info: (今天 - Liz) 這裡的 currencyId 是從 getServerSideProps 取得的
}
```

```ts
interface ITop100HolderSectionProps {
  chainId: string;
  currencyId: number; // 改回 string
  unit: string;
}
```

src/lib/common.ts
```ts
export const getCurrencyIcon = (currencyId: string) => {
  // Info: (20240206 - Julian) 如果沒有 currencyId，就顯示 default_currency.svg
  if (!currencyId) return {src: DEFAULT_CURRENCY_ICON, alt: 'currency_icon'};
  return {
    src: `/currencies/${currencyId}.svg`,
    alt: `currency_icon`,
  };
};
```

**Comment by godmmt** [comment]
# currencies DB data:

```json
[
  {
    "id": 1,
    "address": "0x0000000000000000000000000000000000000000",
    "risk_level": "1",
    "price": 0,
    "volume_in_24h": "0",
    "symbol": "BLT",
    "total_amount": "41199000000000000000000",
    "holder_count": 0,
    "total_transfers": 0,
    "chain_id": 58017,
    "name": "BOLT",
    "decimals": 18
  },
  {
    "id": 2,
    "address": "0x0000000000000000000000000000000000000000",
    "risk_level": "1",
    "price": 0,
    "volume_in_24h": "0",
    "symbol": "ISC",
    "total_amount": "17491000000000000000000",
    "holder_count": 0,
    "total_transfers": 0,
    "chain_id": 8017,
    "name": "iSunCoin",
    "decimals": 18
  }
]
```

### 畫面 check:

<img width="1129" alt="截圖 2024-07-09 下午2 54 39" src="https://github.com/CAFECA-IO/BAIFA/assets/105651918/6b4e46f7-6242-40e5-a548-da16ea588d66">


<img width="1154" alt="截圖 2024-07-09 下午2 52 13" src="https://github.com/CAFECA-IO/BAIFA/assets/105651918/03351394-74d0-4157-9485-44b7286d49d7">

**Comment by godmmt** [comment]
修改： currencyId → string


src/pages/app/currencies/[currencyId]/red-flag.tsx
```ts
interface IRedFlagOfCurrencyPageProps {
  currencyId: string;
}
```

**Comment by godmmt** [comment]
也可以換個做法
採用 number

重構此部分
讓前後端和資料庫的型別可以一致

**Comment by godmmt** [comment]
這個文件感覺需要重構...

**Comment by godmmt** [comment]
currencies 需要重構 有點亂

**Comment by godmmt** [comment]
只有 CurrencyItem 這個元件的 props 設定是 currencyId: number
(CurrenciesPage → AllCurrenciesPageBody → CurrencyItem)

原因是因為這裡的邏輯是直接拿取後端回傳的資料庫的資料
所以採用後端型別 number

其他的頁面保留使用 currencyId: string
原因是因為那是從路徑得來的
由路徑得到的 currencyId 去打 API 找是否有相關的資料
如果沒有找到該筆資料就會顯示 no data 

src/pages/app/currencies/[currencyId]/index.tsx
src/components/top_100_holder_section/top_100_holder_section.tsx
src/pages/app/currencies/[currencyId]/red-flag.tsx
src/lib/common.ts

**Comment by godmmt** [comment]
took 4 hours

done.
